---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
patchesJson6902:
  - path: ./mysql-image-patch-for-4.7.yaml
    target:
      group: apps.openshift.io
      version: v1
      kind: DeploymentConfig
      name: mysql
patchesStrategicMerge:
  - ./shipping-patch-for-4.7.yaml