---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: robot-shop
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- '*'
users:
- system:admin
- system:serviceaccount:robot-shop:robot-shop
defaultAddCapabilities:
- NET_ADMIN