---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    service: mysql
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: robot-shop
      containers:
      - name: mysql
        image: robotshop/rs-mysql-db:latest
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 200m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 400Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/lib/mysql/data"
          name: mysql-data-volume
      restartPolicy: Always
      volumes:
      - name: mysql-data-volume
        persistentVolumeClaim:
          claimName: mysql-data-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-volume-claim
  namespace: robot-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
