---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    service: ratings
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ratings
  template:
    metadata:
      labels:
        service: ratings
    spec:
      containers:
      - name: php-fpm
        image: php:7.0-fpm
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
      - name: ratings
        image: docker.io/pranavgaikwad/robot-shop-ratings:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
