---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
patches:
  - path: ./gluster-patch-for-3.x.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
