---
kind: ProjectRequest
apiVersion: v1
metadata:
  name: rocket-chat

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-chat-db
  namespace: rocket-chat
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: rocketchat-db
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-chat
  namespace: rocket-chat
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: rocketchat
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rocketchat-db
  labels:
    app: rocketchat-db
  namespace: rocket-chat
spec:
  replicas: 1
  selector:
    app: rocketchat-db
  strategy:
    type: Recreate
    recreateParams:
      post:
        failurePolicy: ignore
        execNewPod:
          volumes:
            - rocketchat-data-vol
          containerName: rocketchat-db
          command:
            - /bin/sh
            - -c
            - "sleep 60 && mongo rocket-chat-db:27017 --eval \"rs.initiate({_id: 'rs0', members: [{_id:0, host:'localhost:27017'}]})\""
  template:
    metadata:
      labels:
        app: rocketchat-db
    spec:
      containers:
        - name: rocketchat-db
          image: docker.io/mongo:4.0
          # image: registry.access.redhat.com/rhscl/mongodb-26-rhel7:latest
          command:
            - /bin/sh
            - -c
            - mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
          env:
            - name: MONGODB_USER
              value: rocketchat
            - name: MONGODB_PASSWORD
              value: r0Ck3tChaT
            - name: MONGODB_DATABASE
              value: rocketchat
            - name: MONGODB_ADMIN_PASSWORD
              value: R0cK3TcHAt
          volumeMounts:
            - name: rocketchat-data-vol
              mountPath: /data/db
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: rocketchat-data-vol
          persistentVolumeClaim:
            claimName: rocketchat-data-claim
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rocketchat
  namespace: rocket-chat
  labels:
    app: rocketchat
spec:
  replicas: 1
  selector:
    app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
        - name: rocketchat
          # image: docker.io/mongoclient/mongoclient:2.2.0 # rocket.chat:2.4.9
          image: rocket.chat:2.4.9
          env:
            - name: MONGO_URL
              value: "mongodb://rocketchat:r0Ck3tChaT@rocket-chat-db:27017/rocketchat"
            - name: MONGO_OPLOG_URL
              value: "mongodb://rocket-chat-db:27017/local"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
      restartPolicy: Always

