---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: producer-state
  labels:
    app: bm-amq-producer
  namespace: amq-producer
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
