---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
patches:
  - path: ./php-patch-for-4.7.yaml
    target:
      group: build.openshift.io
      version: v1
      kind: BuildConfig
